highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://thuong89.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Thuong Nguyen's Resume
name: Thuong Nguyen
email: thuong.nguyen@integrify.io
email_full: mailto:youremail@me.com
website: github.io/sustain
website_full: https://thuong89.github.io/sustain
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Kirjurinkuja
  postcode: "02600"
  city: Espoo
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
